FROM ubuntu:20.04 

LABEL maintainer="vishrut@pdx.edu"

RUN apt-get update -y 
RUN apt-get install -y python3-pip 

COPY . /app 

WORKDIR /app 

RUN pip install -r requirements.txt 

ENTRYPOINT ["python3"]

CMD ["app.py"] 
